#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [[ "$DISTRO_NAME" == "openeuler" ]]; then
    echo "No sudoers file for openueler, skipping..."
    exit 0
fi

sed -i -e "/secure_path/ s@\([\'\"]\?\)\$@:/usr/local/bin/\1@" /etc/sudoers
visudo -c
